## LEARN NUMPY 

In [69]:
import numpy as np

### Creating array

In [75]:
arr_1d = np.array([1,2,3,4,5])
print("1D ARRAY: ",arr_1d)

arr_2d = np.array([
    [1,2,3,4,5],
    [5,4,3,2,1],
    [11,22,33,44,55],
    [11,22,33,44,55],
    [11,22,33,44,555]
])
print("2D ARRAY: ",arr_2d)
arr_2d.shape
print(arr_2d[1,2])

1D ARRAY:  [1 2 3 4 5]
2D ARRAY:  [[  1   2   3   4   5]
 [  5   4   3   2   1]
 [ 11  22  33  44  55]
 [ 11  22  33  44  55]
 [ 11  22  33  44 555]]
3


### Check dimention of the array

In [84]:
print(arr_1d,"\nDim:",arr_1d.ndim)
print(arr_2d,"\nDim:",arr_2d.ndim)

[1 2 3 4 5] 
Dim: 1
[[  1   2   3   4   5]
 [  5   4   3   2   1]
 [ 11  22  33  44  55]
 [ 11  22  33  44  55]
 [ 11  22  33  44 555]] 
Dim: 2


### Check no of element in array

In [87]:
print(arr_1d.shape)
print(arr_1d.ndim)
print(arr_2d.shape)
print(arr_2d.ndim)

(5,)
1
(5, 5)
2


### Check version of numpy

In [76]:
print(np.__version__)

2.0.1
